version: '3'

services:
  jenkins:
    build:
      context: .
    image: wachira90/jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/tmp/home:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
